#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinClassification.Resource", IsApplication=true)]

namespace XamarinClassification
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int activity_bg = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int activity_graybg = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int activity_orangebg = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int black_black_text_color = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int black_text_color = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int blue_text_color = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int gray_bg_color = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int gray_line_color = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int gray_text_color = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int green_text_color = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int my_head_bg = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int my_radiogroup_bg = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int my_text_color = 2130968596;
			
			// aapt resource value: 0x7f040009
			public const int order_list_item_bg = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int pink_bg_color = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int pink_light_bg_color = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int press_click_color = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int press_normal_color = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int red_text_color = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int top_color = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int white_text_color = 2130968590;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int erpx = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int image_def_size = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int line_gray_halving_height = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int more_left_right_padding = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int more_right_margin = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int more_top_bottom_padding = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int more_top_margin = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int shiSP = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int shiba = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int shier = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int text_big_size = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int text_mid_size = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int text_small_size = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int text_toosmall_size = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int wushipx = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int yipx = 2131034117;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back_btn_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barcode_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bing_input_edt = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int city_small_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int close_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int diannao = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dianqi = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int goicon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int huazhuang = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int line = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int lottery_list_selector_disabled_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int nanzhuang = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int nav_a_click = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int nav_a_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int nav_b_click = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int nav_b_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int nav_c_click = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int nav_c_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int nav_d_click = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int nav_d_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int nav_e_click = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int nav_e_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int nav_top_line = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int neiyi = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int nvxie = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int nvzhuang = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int product_type_icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int search_btn_bg = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int search_layout_bg = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int shouji = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int shuji = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int transparent_edittext_bg = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int wanju = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int yingshi = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int yiyong = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000f
			public const int action_settings = 2131296271;
			
			// aapt resource value: 0x7f090002
			public const int goods_pager = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int hint_img = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int line = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int listView = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int progressBar = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int text = 2131296263;
			
			// aapt resource value: 0x7f090001
			public const int tools = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int tools_scrlllview = 2131296256;
			
			// aapt resource value: 0x7f09000e
			public const int top_exit = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int top_left_btn = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int top_right_btn = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int top_text = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int toptype = 2131296259;
			
			// aapt resource value: 0x7f090009
			public const int typeicon = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int typename = 2131296266;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_b = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_pro_type = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_b_top_nav_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_pro_type_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int top_bar = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int action_settings = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int cancel = 2131099670;
			
			// aapt resource value: 0x7f060004
			public const int exit = 2131099652;
			
			// aapt resource value: 0x7f060019
			public const int fz_zhenghei_typeface = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int generalhint = 2131099672;
			
			// aapt resource value: 0x7f060002
			public const int hello_world = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int noNet = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int nonet = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int photograph = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int pull_to_refresh_footer_pull_label = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int pull_to_refresh_footer_refreshing_label = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int pull_to_refresh_pull_label = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int pull_to_refresh_refreshing_label = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int pull_to_refresh_release_label = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int pull_to_refresh_tap_label = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int saotext = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int search_hint = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int selectfhote = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int selectimage = 2131099655;
			
			// aapt resource value: 0x7f060017
			public const int submiting = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int sure = 2131099669;
			
			// aapt resource value: 0x7f06000f
			public const int toload20 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int toloadfail = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int toloadnomore = 2131099665;
			
			// aapt resource value: 0x7f060005
			public const int typetext = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
